#查询系列api，每6小时调用一次（周六日不启动）
name: Run Api.Read

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 */6 * * 1-5'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests #安装requests模块
      run: |
        pip install requests
    - name: run api.Read #api调用
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息(修改以下，复制增加账号)
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用1
        MS_TOKEN_1: ${{ secrets.LING12001_TOKEN }} 
        CLIENT_ID_1: ${{ secrets.LING12001_ID }}
        CLIENT_SECRET_1: ${{ secrets.LING12001_SECRET }}
        #账号/应用2
        MS_TOKEN_2: ${{ secrets.LING12002_TOKEN }} 
        CLIENT_ID_2: ${{ secrets.LING12002_ID }}
        CLIENT_SECRET_2: ${{ secrets.LING12002_SECRET }}
        #账号/应用3
        MS_TOKEN_3: ${{ secrets.ZOE11101_TOKEN }} 
        CLIENT_ID_3: ${{ secrets.ZOE11101_ID }}
        CLIENT_SECRET_3: ${{ secrets.ZOE11101_SECRET }}
        #账号/应用4
        MS_TOKEN_4: ${{ secrets.ZOE11102_TOKEN }} 
        CLIENT_ID_4: ${{ secrets.ZOE11102_ID }}
        CLIENT_SECRET_4: ${{ secrets.ZOE11102_SECRET }}
        #账号/应用5
        MS_TOKEN_5: ${{ secrets.ZOE12001_TOKEN }} 
        CLIENT_ID_5: ${{ secrets.ZOE12001_ID }}
        CLIENT_SECRET_5: ${{ secrets.ZOE12001_SECRET }}
        #账号/应用6
        MS_TOKEN_6: ${{ secrets.ZOE12002_TOKEN }} 
        CLIENT_ID_6: ${{ secrets.ZOE12002_ID }}
        CLIENT_SECRET_6: ${{ secrets.ZOE12002_SECRET }}
      run: |
        python ApiOfRead.py
